### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by freaky1337** [emily33901/2015-load-library-injector#1]
I scanned it and my anti-virus said it is a IDP.ALEXA.51 virus

**Comment by josh33901** [comment]
build it yourself then

**Comment by freaky1337** [comment]
Done

**Comment by freaky1337** [comment]
I put junkcodes into it to make it UD

**Comment by freaky1337** [comment]
Avast said it's infected with idp.alexa.51

**Comment by iDaark** [comment]
@josh33901 is it still undetected tho? im willing to use it as base, but i don't want to lose my time k. sorry for posting it there, since github doens't has private message shit, the only way i found to contact you was here.

**Comment by josh33901** [comment]
I have been using it since 2015 - which suggests to me that it is undected.
